const express = require("express");
const router=express.Router();
const resend=require('../config/mailer');


router.post("/", async (req,res)=>{

  const {Name,Email,Phone,Service} = req.body;
  const AdminMail={
    from: "Prakriti Interiors <onboarding@resend.dev>",

            to: process.env.EMAIL_USER,

         subject: `New Consultation Request • ${Name}`,

  html: `
  <div style="
      max-width:650px;
      margin:auto;
      background:#ffffff;
      border:1px solid #e5e5e5;
      border-radius:10px;
      font-family:Arial,sans-serif;
      overflow:hidden;
  ">

      <!-- Header -->

      <div style="
          background:#111315;
          color:#D4AF37;
          padding:20px 30px;
      ">

          <h2 style="margin:0;">
              Prakriti Interiors
          </h2>

          <p style="
              margin:8px 0 0;
              color:#cccccc;
          ">
              New Consultation Request
          </p>

      </div>

      <!-- Body -->

      <div style="padding:30px;">

          <p style="
              color:#555;
              line-height:1.8;
          ">
              A customer has submitted a consultation request through your website.
          </p>

          <table style="
              width:100%;
              border-collapse:collapse;
              margin-top:25px;
          ">

              <tr>
                  <td style="
                      padding:14px;
                      background:#f7f7f7;
                      font-weight:bold;
                      width:35%;
                  ">
                      Name
                  </td>

                  <td style="
                      padding:14px;
                      border-bottom:1px solid #eee;
                  ">
                      ${Name}
                  </td>
              </tr>

              <tr>
                  <td style="
                      padding:14px;
                      background:#f7f7f7;
                      font-weight:bold;
                  ">
                      Email
                  </td>

                  <td style="
                      padding:14px;
                      border-bottom:1px solid #eee;
                  ">
                      ${Email}
                  </td>
              </tr>

              <tr>
                  <td style="
                      padding:14px;
                      background:#f7f7f7;
                      font-weight:bold;
                  ">
                      Phone
                  </td>

                  <td style="
                      padding:14px;
                      border-bottom:1px solid #eee;
                  ">
                      ${Phone}
                  </td>
              </tr>

              <tr>
                  <td style="
                      padding:14px;
                      background:#f7f7f7;
                      font-weight:bold;
                  ">
                      Project
                  </td>

                  <td style="padding:14px;">
                      ${Service}
                  </td>
              </tr>

          </table>

          <div style="
              margin-top:25px;
              padding:15px;
              background:#FFF8E5;
              border-left:4px solid #D4AF37;
              color:#555;
          ">

              <strong>Next Step:</strong><br>

              Contact the customer within 24 hours to discuss the project.

          </div>

      </div>

      <!-- Footer -->

      <div style="
          padding:18px;
          text-align:center;
          background:#fafafa;
          color:#777;
          font-size:13px;
      ">

          This email was automatically generated by the
          <strong>Prakriti Interiors</strong> website.

      </div>

  </div>
  `
  };
    
try {
    
    await resend.emails.send(AdminMail);
     res.status(200).json({
            message: "Email sent successfully"
        });

} catch (error) {
    res.status(500).json({
            message: "Failed to send email"
        });
        console.log(error);

}

})
module.exports=router;
